# -*- coding: utf-8 -*-
"""prompt_strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11aUjsUS6s9OaQbwM6278zf942kdLCGT-
"""

# --- Prompt Engineering Strategy Implementation ---

# Track user choices
user_actions = []

# Show Initial Prompt
def show_initial_prompt():
    print("\n Welcome to the Interactive AI Storyteller! \n")
    print("To begin:")
    print("1) Upload an image to set the scene")
    print("2) Speak or write about your character\n")

# Ask user to choose (upload image or write character)
def ask_user_choice():
    choice = input("Please choose (1/2): ").strip().lower()
    if choice == "1":
        print("\n  You chose to upload an image to set the scene!\n")
        return choice
    elif choice == "2":
        print("\n You chose to speak or write about your character!\n")
        return choice
    else:
        print("\n Invalid choice. Please type '1' or '2'.\n")
        return ask_user_choice()  # ask again until correct

# Handle Image Upload Interaction - simulation
def handle_image_upload():
    print("\n [Image uploaded placeholder]")
    # Image would be sent to multimodal processing
    scene_description = "[Scene description extracted by Multimodal Processing]"
    return scene_description

# Input validation
def get_valid_input(prompt_text):
    while True:
        user_input = input(prompt_text).strip()
        if user_input:
            return user_input
        print("Please enter something.\n")

# Handle Text Input for Character Description
def handle_text_input():
    print("\nPlease describe your character and what they want to do.")
    print("Example: 'I am a brave knight searching for a lost relic.'")
    user_text = get_valid_input("> ")
    return user_text

# Provide a default scene if no image is uploaded
def default_scene():
    return "A vast, open field under a bright blue sky, with a single oak tree in the distance."

# Handle choice logic
def handle_choice(choice):
    if choice == "1":
        scene_description = handle_image_upload()
        if "[Scene description" in scene_description:
            print("No scene detected from image. Using default scene.")
            scene_description = default_scene()
    else:
        scene_description = default_scene()
    text_input = handle_text_input()
    return scene_description, text_input

# Character description and goal extraction with fallback logic
def extract_character_and_goal(text_input):
    if "I am" in text_input:
        parts = text_input.split("I am", 1)[1].strip()
        if "searching for" in parts:
            character, goal = parts.split("searching for", 1)
            character_description = character.strip()
            goal_description = "searching for " + goal.strip()
        elif "trying to" in parts:
            character, goal = parts.split("trying to", 1)
            character_description = character.strip()
            goal_description = "trying to " + goal.strip()
        else:
            character_description = parts
            goal_description = "Unknown goal"
    else:
        character_description = text_input
        goal_description = "Unknown goal"

    if not character_description:
        character_description = "An unnamed adventurer"
    if goal_description == "Unknown goal":
        goal_description = "surviving in a mysterious land"

    return character_description, goal_description

# START prompt
def assemble_prompt(scene_description, character_description, goal_description):
    prompt = f"""
You are a creative AI storyteller.

[Scene Description]: {scene_description}

[Character Description]: {character_description}

[Goal]: {goal_description}

Instructions:
- Create a vivid, engaging story starting from the scene and character provided.
- Ensure logical story progression.
- At the end, suggest 3 possible actions the user can choose to continue the story.
- Additional Options: Choose Your Own Action, Open Inventory, End Story.
"""
    return prompt

# CONTINUE prompt (based on architecture)
def assemble_continue_prompt(scene_description, user_input, story_history):
    prompt = f"""
You are a creative AI storyteller.

[Scene Description]: {scene_description}
(Extracted elements: setting, characters, mood)

[User Prompt]: {user_input}

[Story History]: {story_history}

Instructions:
- Continue the story in a vivid and engaging tone.
- Build upon the user's action while maintaining logical consistency with the story so far.
- End with 3 suggested options for what the user can do next.
- Additional Options: Choose Your Own Action, Open Inventory, End Story.
"""
    return prompt

# Truncate story history to last 3 paragraphs
def truncate_story(story, max_paragraphs=3):
    paragraphs = [p for p in story.strip().split('\n') if p.strip()]
    return '\n'.join(paragraphs[-max_paragraphs:])

# TODO: Replace this function when the Story Generator module is complete.
# Simulate model response, with optional debug printing
def send_to_story_generator(prompt, debug=True):
    if debug:
        print("\n--- Final Assembled Prompt ---")
        print(prompt)
    else:
        print("\n[ Prompt sent to Story Generator Module. ]")
# Example (replace this with actual model call):
    # response = generate_story_from_prompt(prompt)
    # return response


# CONTINUE logic with improved story update
def continue_story(scene_description, character_description, story_so_far):
    user_input = get_valid_input("\nWhat would your character like to do next?\n> ")
    user_actions.append(user_input)

    short_story = truncate_story(story_so_far)
    prompt = assemble_continue_prompt(scene_description, user_input, short_story)

    # Send prompt (currently prints, but will call the model in future)
    send_to_story_generator(prompt)

    # TODO: Replace the simulated story update below with actual model output
    # Example:
    # response = generate_story_from_prompt(prompt)
    # story_update = response

    # Simulate continuation update based on input
    story_update = f"{user_input.capitalize()}. Something unexpected follows..."
    updated_story = story_so_far + '\n' + story_update

    return updated_story

# Main interaction flow
def run_interactive_story():
    show_initial_prompt()
    choice = ask_user_choice()
    scene_description, text_input = handle_choice(choice)
    character_description, goal_description = extract_character_and_goal(text_input)

    # START story
    initial_prompt = assemble_prompt(scene_description, character_description, goal_description)
    send_to_story_generator(initial_prompt)

    story_so_far = f"{character_description} enters the scene. {scene_description}"

    # CONTINUE loop
    while True:
        cont = input("\nWould you like to continue the story? (y/n): ").strip().lower()
        if cont == "y":
            story_so_far = continue_story(scene_description, character_description, story_so_far)
        elif cont == "n":
            print("\nThank you for playing! The story ends here.")
            break
        else:
            print("Please type 'y' or 'n'.")

    # Optional summary of actions
    print("\n Session Summary: Your Character's Decisions")
    for i, action in enumerate(user_actions, 1):
        print(f"{i}. {action}")

# --- Execute ---
if __name__ == "__main__":
    run_interactive_story()